export type LocaleKey = "es" | "en" | "fr" | "ru";
export type ThemeMode = "light" | "dark";
export type Role = "admin" | "user";
export type OAuthProvider = "google" | "facebook" | "instagram" | "linkedin";

export type TranslationDictionary = {
  appName: string;
  appSubtitle: string;
  today: string;
  admin: string;
  user: string;
  manageUsers: string;
  logout: string;
  monthSummary: string;
  monthCharts: string;
  noData: string;
  editRecord: string;
  createRecord: string;
  language: string;
  darkMode: string;
  lightMode: string;
  legendBad: string;
  legendNormal: string;
  legendGreat: string;
  legendGoal: string;
  weekdays: string[];
  dailyLog: string;
  howAreYou: string;
  mood: string;
  mentalState: string;
  physicalState: string;
  sleep: string;
  sleepQuality: string;
  sleepHours: string;
  dailyGoals: string;
  nutrition: string;
  exerciseDone: string;
  exerciseType: string;
  exercisePlaceholder: string;
  minutes: string;
  leisureDone: string;
  leisureActivity: string;
  leisurePlaceholder: string;
  notes: string;
  notesPlaceholder: string;
  save: string;
  saving: string;
  saved: string;
  deleted: string;
  deleteRecord: string;
  moodLabels: string[];
  avgMood: string;
  avgMental: string;
  avgPhysical: string;
  avgSleep: string;
  avgSleepHours: string;
  exercise: string;
  food: string;
  leisure: string;
  daysAchieved: string;
  trends: string;
  sleepChart: string;
  profile: string;
  goals: string;
  dailyRatings: string;
  sleepHoursPerDay: string;
  wellnessProfile: string;
  goalsCompletion: string;
  average: string;
  maximum: string;
  minimum: string;
  globalGoalAvg: string;
  chartMood: string;
  chartMental: string;
  chartPhysical: string;
  chartSleep: string;
  chartHours: string;
  chartExercise: string;
  chartFood: string;
  chartLeisure: string;
  chartCompletion: string;
  noRecord: string;
  sleepHoursLabel: string;
  exerciseDetail: string;
  leisureDetail: string;
  notesDetail: string;
  foodGoal: string;
  exerciseGoal: string;
  leisureGoal: string;
  inviteUser: string;
  invitePlaceholder: string;
  inviteSuccess: string;
  roleLabel: string;
  pendingInvites: string;
  createdAt: string;
  actions: string;
  backToDashboard: string;
  selectDayHint: string;
  quickView: string;
  close: string;
  completedGoals: string;
  deliveryStatus: string;
  resendInvite: string;
  emailSent: string;
  emailPending: string;
  emailFailed: string;
  inviteCreatedWithEmail: string;
  inviteCreatedNoEmail: string;
  inviteCreatedWithFailure: string;
  copyLink: string;
  copied: string;
  signIn: string;
  signUp: string;
  signInSubtitle: string;
  signUpSubtitle: string;
  continueWith: string;
  orContinueWith: string;
  googleLabel: string;
  facebookLabel: string;
  instagramLabel: string;
  linkedinLabel: string;
  socialLoginUnavailable: string;
  socialLoginNeedsInvitation: string;
  socialLoginFailed: string;
  socialLoginCancelled: string;
  forgotPassword: string;
  forgotPasswordSubtitle: string;
  resetPassword: string;
  resetPasswordSubtitle: string;
  sendResetLink: string;
  resetLinkSent: string;
  resetLinkCopied: string;
  newPassword: string;
  confirmNewPassword: string;
  backToLogin: string;
  resetPasswordSuccess: string;
  resetPasswordInvalid: string;
  resetPasswordExpired: string;
  email: string;
  password: string;
  name: string;
  confirmPassword: string;
  needAccount: string;
  haveAccount: string;
  accessRestricted: string;
  invitationHelp: string;
  monthEmptyTitle: string;
  monthEmptyBody: string;
};

export type EntryRecord = {
  id: string;
  dateKey: string;
  mood: number;
  mentalState: number;
  physicalState: number;
  sleepQuality: number;
  sleepHours: number;
  nutritionDone: boolean;
  exerciseDone: boolean;
  exerciseType: string | null;
  exerciseMinutes: number | null;
  leisureDone: boolean;
  leisureActivity: string | null;
  notes: string | null;
};

export type EntryPayload = Omit<EntryRecord, "id">;

export type InvitationRecord = {
  id: string;
  email: string;
  role: Role;
  token: string;
  acceptedAt: string | null;
  sentAt: string | null;
  lastDeliveryError: string | null;
  createdAt: string;
};

export type DeliveryStatus = "sent" | "pending" | "failed";


export type PublicUser = {
  id: string;
  email: string;
  name: string;
  role: Role;
  preferredLocale: LocaleKey;
  themeMode: ThemeMode;
};
